version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: servik8888/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: servik8888/foodgram_frontend
    depends_on:
      - backend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: servik8888/foodgram_gateway
    depends_on:
      - backend
      - frontend
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media