# Generated by Django 3.2.16 on 2024-01-22 11:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240117_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': 'is_favorited', 'ordering': ('-recipe__created_at',), 'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingrecipe',
            options={'default_related_name': 'is_in_shopping_cart', 'ordering': ('-recipe__created_at',), 'verbose_name': 'Ингредиент для покупки', 'verbose_name_plural': 'Ингредиенты для покупки'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#7aa234', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorite_unique_user_recipe_pair'),
        ),
        migrations.AddConstraint(
            model_name='shoppingrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='shopping_unique_user_recipe_pair'),
        ),
    ]
