# Generated by Django 3.2.16 on 2024-01-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240101_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingingredient',
            options={},
        ),
    ]
