# Generated by Django 3.2.16 on 2024-01-23 10:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240122_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': 'is_favorited', 'ordering': ('recipe__name',), 'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingrecipe',
            options={'default_related_name': 'is_in_shopping_cart', 'ordering': ('recipe__name',), 'verbose_name': 'Ингредиент для покупки', 'verbose_name_plural': 'Ингредиенты для покупки'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#5c8142', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
