# Generated by Django 3.2.16 on 2024-01-24 07:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240124_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#1e18d4', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
