# Generated by Django 3.2.16 on 2024-01-24 12:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ab88db', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
