# Generated by Django 3.2.16 on 2024-01-25 11:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20240124_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#cb470a', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
