# Generated by Django 3.2.16 on 2024-01-25 19:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20240125_1429'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient_pair',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#040a21', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
