# Generated by Django 3.2.16 on 2024-01-25 19:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20240125_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#cc7bb8', image_field=None, max_length=25, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
